on: [push]

jobs:
  amplified_feedback_job:
    runs-on: ubuntu-latest
    name: Amplified Feedback Spike
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
        #Send a slack message that the workflow was triggered
      - name: Amplified Feedback action step
        uses: ./ # Uses an action in the root directory
        id: amplified-feedback
        with:
          slack-token: ${{ secrets.SLACK_TOKEN }} #token used by our app slack bot
          slack-channel: '#cicd-feedback-poc' #cicd-feedback-poc where the slack bot posts the notification
          slack-channel-webhook: ${{ secrets.CHANNEL_CICD_FEEDBACK_POC }}
          message: 'Workflow triggered :nerd_face:' #send a notification that this step in the workflow had been triggered
        #if the above step fails send a slack failure message
      - name: Amplified Feedback Failure
        if: failure()
        uses: ./ # Uses an action in the root directory
        id: amplified-feedback-failure
        with:
          slack-token: ${{ secrets.SLACK_TOKEN }} 
          slack-channel: '#cicd-feedback-poc'
          slack-channel-webhook: ${{ secrets.CHANNEL_CICD_FEEDBACK_POC }}
          message: 'FAILURE :x:'
      - name: Get the output time
        run: echo "The completed time was ${{ steps.amplified-feedback.outputs.time }}"
        #Send slack message the job has completed
      - name: Amplified Feedback Success
        if: success()
        uses: ./ 
        id: amplified-feedback-success
        with:
          slack-token: ${{ secrets.SLACK_TOKEN }} 
          slack-channel: '#cicd-feedback-poc
          ' 
          slack-channel-webhook: ${{ secrets.CHANNEL_CICD_FEEDBACK_POC }}
          message: 'SUCCESS :heavy_check_mark:'